inputSpec: /local/api/client.yaml
outputDir: /local/client
generatorName: go
artifactId: "watchman-client"
gitUserId: moov-io
gitRepoId: "watchman"
additionalProperties:
  isGoSubmodule: true
  packageName: client
