name: Static Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Go Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: stable
      id: go

    - name: Setup Node / NPM
      if: runner.os == 'Linux'
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install make (Windows)
      if: runner.os == 'Windows'
      run: choco install -y make mingw

    - name: Docker Build
      if: runner.os == 'Linux'
      run: make docker-static
